name: Nixer Documentation
title: nixer-io
description: Nixer Spring Plugin documentation
email: contact@nixer.io
url: http://nixer-io.github.io
baseurl: ""

project:
    version: 0.1.1.0
    github_url: https://github.com/nixer-io/nixer-spring-plugin

license:
    software: Apache License Version 2.0
    software_url: https://www.apache.org/licenses/LICENSE-2.0

links:
    header:
      - title: GitHub
        url: https://github.com/nixer-io/nixer-spring-plugin
    footer:
      - title: GitHub
        url: https://github.com/nixer-io/nixer-spring-plugin

ui:
    header:
        color1: "#0a64a0"
        color2: "#042840"
        trianglify: true

social:
    github:
        enabled: false
        user:
        repo:
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google:

# Build settings
markdown: kramdown
kramdown:
    input: GFM
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor
    - .idea/
